### ISSUE TITLE
Research 311 mobile best practices

### ISSUE THREAD

**Issue by taitcha** [Chicago/design-projects#16]
- [x]  Review peer cities (including Denver, Boston, etc.)
- [x]  Find and catalog patterns/best practices/issues to avoid
- [x]  Put together sharable report (Google Slides? or other)
- [ ]  Review internally, then share report

**Comment by dekdekdek** [comment]
I just gathered some cities 311 pages. Need to put them in a powerpoint.

**Comment by dekdekdek** [comment]
I'll update.

**Comment by taitcha** [comment]
311 Mobile Site research draft: https://docs.google.com/presentation/d/1Mn_kGzSVdqGRYEiPohxNGORzHErZ4FdGJoX9YRmBvoY/edit

**Comment by dekdekdek** [comment]
updated the slides. show it on Tuesday(July 17th)

**Comment by jdkunesh** [comment]
This work is done.
