### ISSUE TITLE
Interface Inventory

### ISSUE THREAD

**Issue by taitcha** [Chicago/design-projects#21]
We need to perform an interface inventory across key properties:

- [x] Coc.org
- [ ] Pay.coc.org
- [ ] 311
- [ ] Chicago business direct
- [ ] Buildings app

**Comment by taitcha** [comment]
https://docs.google.com/presentation/d/1ilKpx3JWOLZjptjJktPFwnrhgJXN7m8rZNwu-cJ3QBk/edit

**Comment by jdkunesh** [comment]
calling this work complete, as it will be revisited in the new rebranding work.
