### ISSUE TITLE
311 Community Portal service request detail page status views

### ISSUE THREAD

**Issue by jdkunesh** [Chicago/design-projects#4]
For users of the community portal to understand the status of a service request and the associated work activity, the service request detail page will display a visual representation of this status with supporting text and actions for the user to take on that request.

**Comment by taitcha** [comment]
Service Status UI Inventory: https://docs.google.com/presentation/d/1hG3IZT6PfebbrYnjU78nV4kkZ_cq0CA6Z-RZaytdPuw/edit

**Comment by taitcha** [comment]
Service Status wireframe ideas: https://www.figma.com/file/aLLkrDnJVxiuaws2IoliIuso/Service-Status-Ideas
