### ISSUE TITLE
Convert CDS.org to USDS one-pager

### ISSUE THREAD

**Issue by taitcha** [Chicago/design-projects#43]
- [x] Choose/modify USDS Jekyll/Federalist template
- [x] Write intro on CDS House style over 18F/USDS standards
- [x] Consolidate content to single page
- [x] Fork 18f Method cards
- [x] Update Method cards fork
- [x] Fork USDS Design patterns library
- [x] Update Design patterns library
- [x] Fork 18f Accessibility guide

**Comment by jdkunesh** [comment]
https://chicagodesignsystem.org/ description and purpose updated.
