### ISSUE TITLE
Comprehensible Chicago

### ISSUE THREAD

**Issue by jdkunesh** [Chicago/design-projects#50]
As part of a digital communications strategy for data transparency, the Mayor's Office has asked DoIT to "review the city's website and digital communications for usability, language, and disability access, and other under-utilized opportunities."
We have performed these reviews in an ad hoc fashion before. I can summarize the results here: generally terrible, mostly fixable but through changing how we work as much as how we change our technology.

This project, then would be an effort to:

1. catalog these findings so others are aware of our current state (1 week).
1. determine which languages we will seek to support, and how (1 week).
1. determine gaps in our current processes for content production that impact accessibility, readability/reading level.
1. recommend changes or future work to address how content is produced and published across our primary city properties.
1. produce a presentation, pdf and web site report of the process and findings. 

For the purposes of this project, our scope is limited to chicago.gov, 311.chicago.gov, pay.chicago.gov, and the CHI311 mobile application.

# Catalog our current state

Using http://juicystudio.com/services/readability.php which uses three metrics to evaluate readability, we see chicago.gov requires more than a high school education to read.

Install https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk?hl=en & https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh?hl=en-US

See more about their usage here: https://developers.google.com/web/tools/lighthouse/#devtools 

Review chicago.gov's home page, a department page, a program page, and a promotional page.
For 311.chicago.gov, the home page, a knowledge article, and a service request submission.
For pay.chicago.gov, the home page, help content, and the process of paying a parking ticket.
For the CHI311 mobile application, the same items as 311.chicago.gov. 

# Language support & best practices

We determined the City of Chicago will support English, Spanish, Mandarin Chinese, Polish, Arabic, & Tagalog languages as a response to the [language access ordinance](https://igchicago.org/2018/08/23/language-access-ordinance-compliance-audit-follow-up-inquiry/). Please help document and define our standard for language translation services. We have performed some due diligence with language translation service providers. We need to examine how tools like Google or Bing may be supplemented with additional translation work performed for high use cases.

How should this be considered and implemented consistently? What is an ideal content workflow that supports our multiple content authors?

# Gap analysis of today's workflow 

Where are we missing readability, accessibility and internationalization support in our current workflow?

# What changes can we make to our workflow to improve comprehension?

What are a list of suggested interventions, from small to large, that could help us?

# Artifacts

From this work, we should expect a report, a web page presentation, and a written report.

**Comment by jdkunesh** [comment]
https://www.plainlanguage.gov/guidelines/ for a good overview of helpful content generation tips.

**Comment by jdkunesh** [comment]
Hi @Jpaezhill-

Any progress to report?

**Comment by Jpaezhill** [comment]
Yes! I'll send over a first draft to you end of the week or early next week. @jdkunesh

**Comment by jdkunesh** [comment]
Hi @Jpaezhill! Great job on the first draft. 

I'd like to include a short synopsis of this current information. It's decades in the making, so if this ruling stands it means a sea change in the way sites services are made accessible today.

Domino's lawsuit WCAG 2.0 A ruling information:

https://popculture.com/trending/2019/08/02/dominos-fights-accessibility-ruling-supreme-court-social-media-weighs-in/

https://www.washingtonpost.com/politics/courts_law/do-protections-for-people-with-disabilities-apply-online-dominos-asks-high-court/2019/07/20/984c685e-a7fd-11e9-a3a6-ab670962db05_story.html

I'll follow up with the URLs for the readability portion in a moment, and then will write up the current and future state tech approaches.

**Comment by jdkunesh** [comment]
Here's a good starting list of pages to evaluate:

https://pay.chicago.gov/faq_tickets
https://www.chicago.gov/city/en/depts/fin/supp_info/revenue/parking_and_red-lightticketpaymentplans.html
https://www.chicago.gov/city/en/depts/fin/supp_info/revenue/challenging_tickets.html
https://www.chicago.gov/city/en/depts/311.html
https://311.chicago.gov/s/?language=en_US
https://311.chicago.gov/s/article/abandoned-vehicles?language=en_US
https://311.chicago.gov/s/article/City-vehicle-stickers?language=en_US

**Comment by jdkunesh** [comment]
Findings were shared with the Office of New Americans and will soon be published on the design team's blog.
