### ISSUE TITLE
Access Chicago Booth

### ISSUE THREAD

**Issue by jdkunesh** [Chicago/design-projects#6]
- get booth

**Comment by jdkunesh** [comment]
# Booth #216

* Booth Equipment
* Booth Size:	 10' x 10'
* Back Wall Drape:	8' High Back wall  Color: Hunter Green & Navy 
* Sidewall Drape:	3' High Side wall  Color: Hunter Green & Navy 
* Table:	1 - 6' Skirted table    Color: Black 
* Chairs:	2 - Chairs 
* Wastebasket:	1 - Wastebasket 
* ID Sign:	1 - Line ID Sign

**Comment by taitcha** [comment]
Draft AccessChicago interview protocol/waiver: https://docs.google.com/document/d/1p08zg760SdQ4FqMNKbwhMJ0i7GiXQBFsOj62t6ppJAU/edit

**Comment by jdkunesh** [comment]
@taitcha this looks awesome.
@dekdekdek could also lend a hand with making sure we're ready to roll for Thursday.

**Comment by jdkunesh** [comment]
oh, and: https://methods.18f.gov/participant-agreement/ has some good things in it to crib from.
